export const FETCH_USERS_LIST_REQUEST = 'FETCH_USERS_LIST_REQUEST';
export const FETCH_USERS_LIST_SUCCESS = 'FETCH_USERS_LIST_SUCCESS';
export const FETCH_USERS_LIST_FAILED = 'FETCH_USERS_LIST_FAILED';
export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILED = 'FETCH_USER_DETAILS_FAILURE';
